server:
  port: 9001

spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mysql://218.84.186.2:30007/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: asdlkjcs2
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # 配置Nacos地址
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${ZIPKIN_HOST:192.168.109.128}:${ZIPKIN_PORT:9411}  # 指定了Zipkin服务器的地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
